apiVersion: apps.mshort55.io/v1
kind: VirtSquad
metadata:
  labels:
    app.kubernetes.io/name: virtsquad-operator
    app.kubernetes.io/managed-by: kustomize
  name: virtsquad-sample
spec:
  oksana:
    name: "oksana-pod"
    replicas: 2
  kurtis:
    name: "kurtis-pod"
    replicas: 1
  matt:
    name: "matt-pod"
    replicas: 1
